export const getTableData = (tabName) => {
  if (tabName === "Overview") {
    return {
      subTabs: [{ name: "Majors" }, { name: "Minors" }, { name: "Exotics" }],
      data: [
        {
          subTab: "Majors",
          "trading-instrument": "AUDUSD",
          "spread-pt": "0.4",
          link: "signup",
        },
        {
          subTab: "Majors",
          "trading-instrument": "EURJPY",
          "spread-pt": "1",
          link: "signup",
        },
        {
          subTab: "Majors",
          "trading-instrument": "EURUSD",
          "spread-pt": "0.1",
          link: "signup",
        },
        {
          subTab: "Majors",
          "trading-instrument": "GBPJPY",
          "spread-pt": "3",
          link: "signup",
        },
        {
          subTab: "Majors",
          "trading-instrument": "GBPUSD",
          "spread-pt": "0.3",
          link: "signup",
        },
        {
          subTab: "Majors",
          "trading-instrument": "USDCAD",
          "spread-pt": "0.7",
          link: "signup",
        },
        {
          subTab: "Majors",
          "trading-instrument": "USDJPY",
          "spread-pt": "0.5",
          link: "signup",
        },
        {
          subTab: "Minors",
          "trading-instrument": "AUDCAD",
          "spread-pt": "0.4",
          link: "signup",
        },
        {
          subTab: "Minors",
          "trading-instrument": "AUDCHF",
          "spread-pt": "1",
          link: "signup",
        },
        {
          subTab: "Minors",
          "trading-instrument": "AUDNZD",
          "spread-pt": "0.1",
          link: "signup",
        },
        {
          subTab: "Minors",
          "trading-instrument": "CADCHF",
          "spread-pt": "3",
          link: "signup",
        },
        {
          subTab: "Minors",
          "trading-instrument": "GBPUSD",
          "spread-pt": "0.3",
          link: "signup",
        },
        {
          subTab: "Minors",
          "trading-instrument": "EURNZD",
          "spread-pt": "0.7",
          link: "signup",
        },
        {
          subTab: "Minors",
          "trading-instrument": "EURNZD",
          "spread-pt": "0.5",
          link: "signup",
        },
        {
          subTab: "Minors",
          "trading-instrument": "EURNZD",
          "spread-pt": "0.5",
          link: "signup",
        },
        {
          subTab: "Exotics",
          "trading-instrument": "USDMXN",
          "spread-pt": "0.4",
          link: "signup",
        },
        {
          subTab: "Exotics",
          "trading-instrument": "USDCNH",
          "spread-pt": "1",
          link: "signup",
        },
        {
          subTab: "Exotics",
          "trading-instrument": "USDSGD",
          "spread-pt": "0.1",
          link: "signup",
        },
        {
          subTab: "Exotics",
          "trading-instrument": "USDTRY",
          "spread-pt": "3",
          link: "signup",
        },
        {
          subTab: "Exotics",
          "trading-instrument": "GBPUSD",
          "spread-pt": "0.3",
          link: "signup",
        },
        {
          subTab: "Exotics",
          "trading-instrument": "USDZAR",
          "spread-pt": "0.7",
          link: "signup",
        },
        {
          subTab: "Exotics",
          "trading-instrument": "GBPSGD",
          "spread-pt": "0.5",
          link: "signup",
        },
        {
          subTab: "Exotics",
          "trading-instrument": "USDCNH",
          "spread-pt": "0.5",
          link: "signup",
        },
        {
          subTab: "Spot Metals",
          "trading-instrument": "XAGEUR",
          "spread-pt": "0.4",
          link: "signup",
        },
        {
          subTab: "Spot Metals",
          "trading-instrument": "XAGUSD",
          "spread-pt": "1",
          link: "signup",
        },
        {
          subTab: "Spot Metals",
          "trading-instrument": "XAUEUR",
          "spread-pt": "0.1",
          link: "signup",
        },
        {
          subTab: "Spot Metals",
          "trading-instrument": "XAUGBP",
          "spread-pt": "3",
          link: "signup",
        },
        {
          subTab: "Spot Metals",
          "trading-instrument": "XAUUSD",
          "spread-pt": "0.3",
          link: "signup",
        },
        {
          subTab: "Spot Metals",
          "trading-instrument": "XPTUSD",
          "spread-pt": "0.7",
          link: "signup",
        },
        {
          subTab: "Spot Metals",
          "trading-instrument": "COPPER",
          "spread-pt": "0.5",
          link: "signup",
        },
      ],
    };
  } else if (tabName === "Forex") {
    return {
      data: [
        {
          symbol: "AUDJPY",
          name: "Australian Dollar/Japanese Yen",
          "min-spreads": "0.4",
          "typical-spreads": "0.9",
          "swap-short": "-2.010762",
          "swap-long": "1.138345",
          "trading-hours": "0:05:00 - 23:55:00",
        },
        {
          symbol: "AUDUSD",
          name: "Australian Dollar/US Dollar",
          "min-spreads": "0.5",
          "typical-spreads": "1",
          "swap-short": "0.145665",
          "swap-long": "-0.448695",
          "trading-hours": "0:05:00 - 23:55:00",
        },
        {
          symbol: "CHFJPY",
          name: "Swiss Franc/Japanese Yen",
          "min-spreads": "0.4",
          "typical-spreads": "0.9",
          "swap-short": "-1.665495",
          "swap-long": "0.695955",
          "trading-hours": "0:05:00 - 23:55:00",
        },
        {
          symbol: "EURAUD",
          name: "Euro/Australian Dollar",
          "min-spreads": "1",
          "typical-spreads": "1.5",
          "swap-short": "-0.229671",
          "swap-long": "-0.54756",
          "trading-hours": "0:05:00 - 23:55:00",
        },
        {
          symbol: "EURCAD",
          name: "Euro/Canadian Dollar",
          "min-spreads": "0.4",
          "typical-spreads": "0.9",
          "swap-short": "0.169403",
          "swap-long": "-0.967356",
          "trading-hours": "0:05:00 - 23:55:00",
        },
        {
          symbol: "EURCHF",
          name: "Euro/Swiss Franc",
          "min-spreads": "0.5",
          "typical-spreads": "1",
          "swap-short": "-1.078389",
          "swap-long": "0.55029",
          "trading-hours": "0:05:00 - 23:55:00",
        },
        {
          symbol: "EURGBP",
          name: "Euro/Great Britain Pound",
          "min-spreads": "0.6",
          "typical-spreads": "1.1",
          "swap-short": "0.19994949",
          "swap-long": "-0.74192859",
          "trading-hours": "0:05:00 - 23:55:00",
        },
        {
          symbol: "EURJPY",
          name: "Euro/Japanese Yen",
          "min-spreads": "0.6",
          "typical-spreads": "1.1",
          "swap-short": "-3.11805",
          "swap-long": "1.825668",
          "trading-hours": "0:05:00 - 23:55:00",
        },
        {
          symbol: "EURUSD",
          name: "Euro/US Dollar",
          "min-spreads": "0.2",
          "typical-spreads": "0.7",
          "swap-short": "0.28160821",
          "swap-long": "-1.04693472",
          "trading-hours": "0:05:00 - 23:55:00",
        },
        {
          symbol: "GBPAUD",
          name: "Great Britain Pound/Australian Dollar",
          "min-spreads": "0.4",
          "typical-spreads": "0.9",
          "swap-short": "-1.175733",
          "swap-long": "0.321542",
          "trading-hours": "0:05:00 - 23:55:00",
        },
        {
          symbol: "GBPCAD",
          name: "Great Britain Pound/Canadian Dollar",
          "min-spreads": "0.3",
          "typical-spreads": "0.8",
          "swap-short": "-0.415233",
          "swap-long": "-0.080613",
          "trading-hours": "0:05:00 - 23:55:00",
        },
        {
          symbol: "GBPCHF",
          name: "Great Britain Pound/Swiss Franc",
          "min-spreads": "0.2",
          "typical-spreads": "0.7",
          "swap-short": "-1.816074",
          "swap-long": "1.048788",
          "trading-hours": "0:05:00 - 23:55:00",
        },
        {
          symbol: "GBPJPY",
          name: "Great Britain Pound/Japanese Yen",
          "min-spreads": "0.6",
          "typical-spreads": "1.1",
          "swap-short": "-4.572126",
          "swap-long": "2.812953",
          "trading-hours": "0:05:00 - 23:55:00",
        },
      ],
    };
  } else if (tabName === "Crypto") {
    return {
      config: {
        thBackgroundColor: "bg-white",
        isPaginated: true,
        hidden: [],
      },
      tabs: [
        { name: "Overview" },
        { name: "Forex" },
        { name: "Crypto" },
        { name: "Spreads" },
      ],
      data: [
        {
          symbol: "BTCUSD",
          name: "Bitcoin vs US Dollar",
          "min-spreads": "44.5",
          "typical-spreads": "65",
          "swap-short": "-3483.9012",
          "swap-long": "-3474.4554",
          "trading-hours": "01:00-24:00",
        },
        {
          symbol: "ETHUSD",
          name: "Ethereum vs US Dollar",
          "min-spreads": "5.08",
          "typical-spreads": "40",
          "swap-short": "-260.7865",
          "swap-long": "-260.5239",
          "trading-hours": "01:00-24:00",
        },
        {
          symbol: "LTCUSD",
          name: "Litecoin vs US Dollar",
          "min-spreads": "11.5",
          "typical-spreads": "19",
          "swap-short": "-6.17617",
          "swap-long": "-6.41095",
          "trading-hours": "01:00-24:00",
        },
        {
          symbol: "XRPUSD",
          name: "Ripple vs US Dollar",
          "min-spreads": "204",
          "typical-spreads": "354",
          "swap-short": "-5.6992",
          "swap-long": "-5.7005",
          "trading-hours": "01:00-24:00",
        },
        {
          symbol: "XLMUSD",
          name: "Stellar vs US Dollar",
          "min-spreads": "7",
          "typical-spreads": "13",
          "swap-short": "6.3219",
          "swap-long": "-24.0201",
          "trading-hours": "01:00-24:00",
        },
        {
          symbol: "DOTUSD",
          name: "Polkadot vs US Dollar",
          "min-spreads": "84",
          "typical-spreads": "140",
          "swap-short": "0.587613",
          "swap-long": "-8.814039",
          "trading-hours": "01:00-24:00",
        },
        {
          symbol: "ZECUSD",
          name: "Zcash vs US Dollar",
          "min-spreads": "68",
          "typical-spreads": "28",
          "swap-short": "-0.728",
          "swap-long": "-0.598",
          "trading-hours": "01:00-24:00",
        },
        {
          symbol: "XMRUSD",
          name: "Monero vs US Dollar",
          "min-spreads": "12",
          "typical-spreads": "20",
          "swap-short": "-7.709",
          "swap-long": "-10.621",
          "trading-hours": "01:00-24:00",
        },
      ],
    };
  } else if (tabName === "Shares") {
    return {
      config: {
        thBackgroundColor: "bg-white",
        isPaginated: true,
        hidden: [],
      },
      tabs: [
        { name: "Overview" },
        { name: "Forex" },
        { name: "Crypto" },
        { name: "Spreads" },
      ],
      data: [
        {
          symbol: "AAL",
          name: "American Airlines Group Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "AAPL",
          name: "Apple",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "ABT",
          name: "Abbot Laboratories",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "ADBE",
          name: "Adobe Systems Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "AIG",
          name: "American International Group",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "AKAM",
          name: "Akamai Technologies Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "ALL",
          name: "Allstate Corp",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "AMZN",
          name: "Amazon Com",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "APA",
          name: "Apache Corp",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "ATHM",
          name: "Autohome Inc",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "ATVI",
          name: "Activision Blizzard Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "AXP",
          name: "American Express",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "BA",
          name: "Boeing",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "BABA",
          name: "Alibaba",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "BAC",
          name: "Bank Of America",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "BBY",
          name: "Best Buy Co Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "BEN",
          name: "Franklin Resources Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "BIDU",
          name: "Baidu Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "BK",
          name: "Bank of New York Mellon Corp",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "BKNG",
          name: "Booking Holdings Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "BLK",
          name: "BlackRock Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "BRKb",
          name: "Berkshire Hathaway Cl B",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "CGC",
          name: "Canopy Growth Corp",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "CMCSA",
          name: "Comcast Corp",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "COIN",
          name: "Coinbase",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "COST",
          name: "Costco Wholesale Corp",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "CRM",
          name: "Salesforce.com Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "CRON",
          name: "Cronos Group Inc",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "CSCO",
          name: "Cisco Systems",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "CVS",
          name: "CVS Health Corp",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "CVX",
          name: "Chevron",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "DAL",
          name: "Delta Air Lines Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "DBX",
          name: "Dropbox Inc",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "DFS",
          name: "Discover Financial Services",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "DIS",
          name: "Walt Disney Company",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "DLTR",
          name: "Dollar Tree Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "EAO",
          name: "Electronic Arts Inc",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "EBAY",
          name: "Ebay",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "EXPE",
          name: "Expedia Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "FB",
          name: "Facebook",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "FDX",
          name: "Fedex",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "GDDY",
          name: "GoDaddy Inc.",
          "trading-hours": "16:30-23:00",
        },
        {
          symbol: "GE",
          name: "General Electric",
          "trading-hours": "16:30-23:00",
        },
      ],
    };
  } else if (tabName === "Commodities") {
    return {
      config: {
        thBackgroundColor: "bg-white",
        isPaginated: true,
        hidden: [],
      },
      tabs: [
        { name: "Overview" },
        { name: "Forex" },
        { name: "Crypto" },
        { name: "Spreads" },
      ],
      data: [
        {
          symbol: "XAGUSD",
          name: "Silver",
          "min-spreads": "85",
          "typical-spreads": "85",
          "swap-short": "2.90334",
          "swap-long": "-5.26266",
          "trading-hours": "1:05:00 - 23:55:00",
        },
        {
          symbol: "XPTUSD",
          name: "Platinum/USD",
          "min-spreads": "31",
          "typical-spreads": "45",
          "swap-short": "-0.72",
          "swap-long": "-12.57",
          "trading-hours": "1:05:00 - 23:55:00",
        },
        {
          symbol: "XAUUSD",
          name: "Gold/US Dollar",
          "min-spreads": "9",
          "typical-spreads": "-37.6395",
          "swap-short": "22.485",
          "swap-long": "-30.18",
          "trading-hours": "1:05:00 - 23:55:00",
        },
        {
          symbol: "UKOIL.c",
          name: "UK Brent (Spot)",
          "min-spreads": "10",
          "typical-spreads": "-4.807",
          "swap-short": "-6.505166667",
          "swap-long": "-5",
          "trading-hours": "3:00:00 - 23:45:00",
        },
        {
          symbol: "USOIL.c",
          name: "US Crude (Spot)",
          "min-spreads": "10",
          "typical-spreads": "-2.5415",
          "swap-short": "-0.9085",
          "swap-long": "-5",
          "trading-hours": "1:00:00 - 23:45:00",
        },
        {
          symbol: "COCOA",
          name: "Cocoa",
          "min-spreads": "25",
          "typical-spreads": "40",
          "swap-short": "-10",
          "swap-long": "-10",
          "trading-hours": "9:45 - 5:30:00 p.m.",
        },
        {
          symbol: "COFFEE",
          name: "Coffee",
          "min-spreads": "22",
          "typical-spreads": "30",
          "swap-short": "-15",
          "swap-long": "-15",
          "trading-hours": "9:15 - 5:30:00 p.m.",
        },
        {
          symbol: "CORN",
          name: "Corn",
          "min-spreads": "50",
          "typical-spreads": "60",
          "swap-short": "-10",
          "swap-long": "-10",
          "trading-hours": "0:05 - 6:00:00 p.m.",
        },
        {
          symbol: "COTTON",
          name: "Cotton",
          "min-spreads": "110",
          "typical-spreads": "130",
          "swap-short": "-7",
          "swap-long": "-7",
          "trading-hours": "1:05 - 6:20:00 p.m.",
        },
        {
          symbol: "NGAS",
          name: "Natural Gas",
          "min-spreads": "10",
          "typical-spreads": "15",
          "swap-short": "-7",
          "swap-long": "-7",
          "trading-hours": "0:00 - 12:00:00 a.m.",
        },
      ],
    };
  } else if (tabName === "Indices") {
    return {
      config: {
        thBackgroundColor: "bg-white",
        isPaginated: true,
        hidden: [],
      },
      tabs: [
        { name: "Overview" },
        { name: "Forex" },
        { name: "Crypto" },
        { name: "Spreads" },
      ],
      data: [
        {
          symbol: "AUS200.c",
          name: "Australia 200",
          "min-spreads": "5",
          "typical-spreads": "7",
          "swap-short": "0.866745",
          "swap-long": "-236.085579",
          "trading-hours": "1:01:00 - 23:59:00",
        },
        {
          symbol: "DE40.c",
          name: "Germany40",
          "min-spreads": "11",
          "typical-spreads": "13",
          "swap-short": "-5.329659653",
          "swap-long": "-448.2583959",
          "trading-hours": "1:01:00 - 23:59:00",
        },
        {
          symbol: "F40.c",
          name: "France 40",
          "min-spreads": "40",
          "typical-spreads": "42",
          "swap-short": "-3.407718132",
          "swap-long": "-305.9329258",
          "trading-hours": "1:01:00 - 23:59:00",
        },
        {
          symbol: "JP225.c",
          name: "Japan 225",
          "min-spreads": "20",
          "typical-spreads": "22",
          "swap-short": "-547.6076673",
          "swap-long": "-530.8441673",
          "trading-hours": "1:01:00 - 23:59:00",
        },
        {
          symbol: "STOXX50.c",
          name: "Europe 50",
          "min-spreads": "15",
          "typical-spreads": "17",
          "swap-short": "-2.047532022",
          "swap-long": "-183.8202099",
          "trading-hours": "1:01:00 - 23:59:00",
        },
        {
          symbol: "UK100.c",
          name: "NASDAQ 100 Index",
          "min-spreads": "100",
          "typical-spreads": "102",
          "swap-short": "18.64036581",
          "swap-long": "-239.7475541",
          "trading-hours": "1:01:00 - 23:59:00",
        },
        {
          symbol: "DJ30.c",
          name: "Wall Street 30",
          "min-spreads": "9",
          "typical-spreads": "11",
          "swap-short": "282.872622",
          "swap-long": "-842.4217513",
          "trading-hours": "9:01:00 - 20:59:00",
        },
        {
          symbol: "US500.c",
          name: "Standard & Poor's 500",
          "min-spreads": "4",
          "typical-spreads": "6",
          "swap-short": "31.657755",
          "swap-long": "-116.1418139",
          "trading-hours": "1:01:00 - 23:59:00",
        },
        {
          symbol: "Nasdaq100",
          name: "NASDAQ 100 Index",
          "min-spreads": "12",
          "typical-spreads": "14",
          "swap-short": "110.2501256",
          "swap-long": "-404.4711816",
          "trading-hours": "1:30:00 - 23:30:00",
        },
        {
          symbol: "ES35.c",
          name: "Spain 35",
          "min-spreads": "10",
          "typical-spreads": "12",
          "swap-short": "-4.70516389",
          "swap-long": "-422.4130341",
          "trading-hours": "1:01:00 - 23:59:00",
        },
        {
          symbol: "HK50.c",
          name: "Hong Kong 50",
          "min-spreads": "20",
          "typical-spreads": "22",
          "swap-short": "54.10428713",
          "swap-long": "-500.3329179",
          "trading-hours": "1:01:00 - 23:59:00",
        },
      ],
    };
  }
};
